//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#ifndef VC8
#define IDR_MYMANIFEST                  1
#else	 
#define IDR_MYMANIFEST                  9999
#endif
#define IDD_DIALOG                      101
#define IDI_ICON                        102
#define IDD_INPUTBOX                    103
#define IDD_UPDATE                      106
#define IDD_ESPIO_MANAG1                107
#define IDI_ICON1                       110
#define IDI_ICON2                       111
#define IDD_CHGSPIO                     125
#define IDD_OPTIONS                     127
#define IDD_OPT_PAGE1                   128
#define IDD_OPT_PAGE2                   129
#define IDD_OPT_PAGE3                   130
#define IDD_ABOUT                       131
#define IDR_MENU                        132
#define IDD_CHOOSELANG                  133
#define IDR_TRAY_MENU                   135
#define IDR_ACCEL                       136
#define IDB_PROJ_SUPPORT                138
#define IDD_POPUP                       139
#define IDB_POPUPBG                     142
#define IDD_ESPIO_MANAG2                144
#define IDD_ESPIO_MANAG3                145
#define IDD_BALANCE                     147
#define IDD_ESP_REPORTS                 149
#define IDC_SIM                         1000
#define IDC_KT_A                        1002
#define IDC_KT_V                        1003
#define IDC_GT_A                        1004
#define IDC_GT_V                        1005
#define IDC_LJ_A                        1006
#define IDC_LJ_V                        1007
#define IDC_SJ_A                        1008
#define IDC_SJ_V                        1009
#define IDC_KR_A                        1010
#define IDC_KR_V                        1011
#define IDC_SS_A                        1012
#define IDC_SS_V                        1013
#define IDC_KOL_A                       1014
#define IDC_KOL_V                       1015
#define IDC_REC_A                       1016
#define IDC_REC_V                       1017
#define IDC_SPIO_A                      1018
#define IDC_SPIO_V                      1019
#define IDC_BOMB_A                      1020
#define IDC_BOMB_V                      1023
#define IDC_SOL_V                       1025
#define IDC_ZERR_A                      1026
#define IDC_ZERR_V                      1027
#define IDC_TS_A                        1028
#define IDC_TS_V                        1029
#define IDC_KT_A_E                      1030
#define IDC_RAK_V                       1031
#define IDC_IC_A                        1032
#define IDC_LL_V                        1033
#define IDC_RAPID                       1034
#define IDC_SL_V                        1035
#define IDC_DEFTF                       1036
#define IDC_GA_V                        1037
#define IDC_NUM_SIM                     1038
#define IDC_IO_V                        1039
#define IDC_KT_V_E                      1040
#define IDC_PLASMA_V                    1041
#define IDC_GT_A_E                      1042
#define IDC_KS_V                        1043
#define IDC_GT_V_E                      1044
#define IDC_GS_V                        1045
#define IDC_LJ_A_E                      1046
#define IDC_WAFF_A                      1047
#define IDC_WAFF_V                      1048
#define IDC_SCHILD_A                    1049
#define IDC_SCHILD_V                    1050
#define IDC_PANZ_A                      1051
#define IDC_PANZ_V                      1052
#define IDC_BEUT_PRAK                   1053
#define IDC_LJ_V_E                      1054
#define IDC_SJ_A_E                      1055
#define IDC_BEUT_TH                     1056
#define IDC_SJ_V_E                      1057
#define IDC_KR_A_E                      1058
#define IDC_KR_V_E                      1059
#define IDC_SS_A_E                      1060
#define IDC_SS_V_E                      1061
#define IDC_KOL_A_E                     1062
#define IDC_KOL_V_E                     1063
#define IDC_REC_A_E                     1064
#define IDC_REC_V_E                     1065
#define IDC_SPIO_A_E                    1066
#define IDC_SPIO_V_E                    1067
#define IDC_BOMB_A_E                    1068
#define IDC_BOMB_V_E                    1069
#define IDC_SOL_V_E                     1070
#define IDC_ZERR_V_E                    1071
#define IDC_ZERR_A_E                    1072
#define IDC_TS_A_E                      1073
#define IDC_TS_V_E                      1074
#define IDC_IC_V                        1075
#define IDC_RAK_V_E                     1076
#define IDC_LL_V_E                      1077
#define IDC_SL_V_E                      1078
#define IDC_GA_V_E                      1079
#define IDC_IO_V_E                      1080
#define IDC_PLASMA_V_E                  1081
#define IDC_KS_V_E                      1082
#define IDC_GS_V_E                      1083
#define IDC_MOND                        1084
#define IDC_VERL_A                      1085
#define IDC_TF                          1086
#define IDC_END                         1087
#define IDC_SCAN_END                    1088
#define IDC_IC_A_E                      1089
#define IDC_VERL_V                      1090
#define IDC_FLUGZEIT                    1091
#define IDC_IC_V_E                      1092
#define IDC_RUNNING_NUM                 1097
#define IDC_BW_CASE                     1098
#define IDC_GEN_READ                    1102
#define IDC_CLOSE                       1104
#define IDC_READ_GEN                    1104
#define IDC_DEL_GEN                     1105
#define IDC_CLIP_COPY                   1120
#define IDC_SHOW_KB                     1126
#define IDC_SHOW_BW                     1129
#define IDC_BILANZ                      1130
#define IDC_CHG_SKIN                    1132
#define IDC_FLYCOST                     1136
#define IDC_LOAD_REM_DEF                1137
#define IDC_BEUT_GES                    1138
#define IDC_UPDATE                      1140
#define IDC_UPD_OUT                     1141
#define IDC_START_UPD                   1142
#define IDC_SPEED_HOME                  1144
#define IDC_DAYLY_UPD                   1145
#define IDC_CHECKTECHS                  1145
#define IDC_ATT1                        1154
#define IDC_ATT2                        1155
#define IDC_ATT3                        1156
#define IDC_DEF1                        1157
#define IDC_DEF2                        1158
#define IDC_DEF3                        1159
#define IDC_S1                          1160
#define IDC_S2                          1161
#define IDC_S3                          1162
#define IDC_S4                          1163
#define IDC_S5                          1164
#define IDC_S6                          1165
#define IDC_S7                          1166
#define IDC_S8                          1167
#define IDC_S9                          1168
#define IDC_S10                         1169
#define IDC_S11                         1170
#define IDC_S12                         1171
#define IDC_S13                         1172
#define IDC_D1                          1173
#define IDC_D3                          1174
#define IDC_D4                          1175
#define IDC_D5                          1176
#define IDC_D6                          1177
#define IDC_D7                          1178
#define IDC_D8                          1179
#define IDC_T1                          1180
#define IDC_T2                          1181
#define IDC_T3                          1182
#define IDC_D2                          1183
#define IDC_USE_SKIN                    1184
#define IDC_S14                         1185
#define IDC_S_POS                       1186
#define IDC_GB_RES                      1187
#define IDC_GB_DEF                      1188
#define IDC_GB_FLEET                    1189
#define IDC_GB_TECHS                    1190
#define IDC_S_WELLBEUT                  1191
#define IDC_S_SPRIT                     1192
#define IDC_S_PRAKBEUT                  1193
#define IDC_S_THBEUT                    1194
#define IDC_S_MOON                      1195
#define IDC_S_LOSSDEF                   1196
#define IDC_S_LOSS_ATT                  1197
#define IDC_S_TF                        1198
#define IDC_S_END                       1199
#define IDC_S_SCAN                      1200
#define IDC_EXIT                        1201
#define IDC_S_GEN_READ                  1204
#define IDC_S_NUMSIM                    1207
#define IDC_SWITCH_FLEET                1208
#define IDC_USE_LANG                    1209
#define IDC_CHG_LANG                    1210
#define IDC_RESET_ATT                   1211
#define IDC_RESET_DEF                   1212
#define IDC_OWN_POS                     1216
#define IDC_DEL_DEF_ON_SWITCH           1218
#define IDC_HOOK_CB                     1220
#define IDC_VERBRENNUNG                 1223
#define IDC_IMPULS                      1224
#define IDC_HYPERRAUM                   1225
#define IDC_SPEED                       1226
#define IDC_S_FLEETSPEED                1227
#define IDC_S_FLYTIME                   1228
#define IDC_S_HYPER                     1230
#define IDC_S_IMPULS                    1231
#define IDC_S_VERBR                     1232
#define IDC_GB_OPT                      1233
#define IDC_SPIOMET                     1235
#define IDC_FLEET_ID                    1235
#define IDC_SPIOKRIS                    1236
#define IDC_SPIODEUT                    1237
#define IDC_SPIOPOS                     1238
#define IDC_DELWAVESTATE                1239
#define IDC_EDIT_SPIO                   1240
#define IDC_SPIONAME                    1240
#define IDC_METAL                       1241
#define IDC_CRYSTAL                     1242
#define IDC_DEUTERIUM                   1243
#define IDC_RES                         1244
#define IDC_POSITION                    1245
#define IDC_OPT_TAB                     1247
#define IDC_OPT_OK                      1250
#define IDC_AUTOSTART                   1251
#define IDC_NEW_FUEL                    1252
#define IDC_OWNSHIPDATA                 1253
#define IDC_OWNRF                       1256
#define IDC_REB_SMALLDEF                1257
#define IDC_S_ENGINES                   1258
#define IDC_LOADRFDATA                  1259
#define IDC_SHOWPOPUP                   1259
#define IDC_LOADSHIPDATA                1260
#define IDC_PREV_FL                     1262
#define IDC_NEXT_FL                     1264
#define IDC_S_FLEETS                    1265
#define IDC_WEBSITE                     1268
#define IDC_IRC                         1269
#define IDC_DEF_REBUILD                 1270
#define IDC_SPEEDUNI                    1271
#define IDC_S_DEF_REBUILD               1272
#define IDC_LANGFILES                   1273
#define IDC_SET_LANG                    1274
#define IDC_SYSTRAY                     1275
#define IDC_TRAY_POPUP                  1276
#define IDC_S_TRAY_POPUP                1277
#define IDC_SINGLE_INST                 1278
#define IDC_TRAY_ON_START               1279
#define IDC_SUPPORT                     1280
#define IDC_OLDSHIELD                   1281
#define IDC_S_PLUNDERTYPE               1282
#define IDC_SHIPTYPE                    1283
#define IDC_S_LOADEDRF                  1284
#define IDC_S_LOADEDSD                  1285
#define IDC_NEXT_TARGET                 1287
#define IDC_PREV_TARGET                 1288
#define IDC_ADD_TARGETINFO              1289
#define IDC_REMOVETARGETINFO            1290
#define IDC_RAIDLISTINFO                1291
#define IDC_RAIDLIST                    1292
#define IDC_GB_RAIDLIST                 1292
#define IDC_PERC_TRACKBAR               1293
#define IDC_REMOVETARGETINFO2           1293
#define IDC_PERC_OUT                    1294
#define IDC_PERC_INFO                   1295
#define IDC_PERC_TRACKBAR2              1296
#define IDC_IS_MOON                     1297
#define IDC_PERC_INFO2                  1297
#define IDC_PERC_OUT2                   1298
#define IDC_BUILD                       1300
#define IDC_TITLE                       1301
#define IDC_GETLANG                     1302
#define IDC_ESPIOAVAIL                  1309
#define IDC_ESPIONEXT                   1310
#define IDC_MOVERIGHT                   1312
#define IDC_MOVELEFT                    1313
#define IDC_MOVEALL                     1314
#define IDC_GB_CHOOSE_REP               1316
#define IDC_GETTEXT                     1317
#define IDC_MAX_ESPIO                   1318
#define IDC_CHECK1                      1319
#define IDC_USE_FLEET                   1319
#define IDC_DISABLE_REP_HIST            1319
#define IDC_OLD_BS                      1319
#define IDC_CHECK2                      1320
#define IDC_USE_RES                     1320
#define IDC_SAVE_REP                    1320
#define IDC_BIG_DF                      1320
#define IDC_CHECK3                      1321
#define IDC_USE_DEF                     1321
#define IDC_BUTTON1                     1322
#define IDC_AS_STANDARD                 1322
#define IDC_DEL_COORD                   1322
#define IDC_BAL_OK                      1322
#define IDC_OPT_CANCEL                  1322
#define IDC_DEL_CUR_REP                 1322
#define IDC_ESPIO_RESULT                1323
#define IDC_ESPIO_INFO                  1324
#define IDC_TO_SIM                      1325
#define IDC_BUTTON2                     1326
#define IDC_TO_RAIDLIST                 1326
#define IDC_CLOSE_ESP_HIST              1326
#define IDC_DONTDEL                     1327
#define IDC_NUMSPIN                     1330
#define IDC_S_LOADED_RF                 1331
#define IDC_S_LOADED_SD                 1332
#define ID_OK                           1333
#define IDC_EINGABE                     1334
#define IDC_OPT_TRANS                   1335
#define IDC_S_SPEED_FACTOR              1337
#define IDC_SPEED_FAC_IN                1339
#define IDC_SPIN_SP_FAC                 1340
#define IDC_S_NAME                      1341
#define IDC_BALANCE_OUT                 1343
#define IDC_REB_BEST                    1346
#define IDC_REB_WORST                   1347
#define IDC_REB_AVG                     1348
#define IDC_S_NEXTWAVE                  1349
#define IDC_S_REBUILD                   1350
#define IDC_REPORT_LIST                 1352
#define IDC_S_INFO_ESP                  1353
#define IDC_S_NONE                      1354
#define IDC_S_ARROW                     1355
#define IDC_NUM_REP                     1356
#define IDC_NUM_REP_T                   1357
#define IDC_EDIT1                       1358
#define IDC_BIG_DF_S                    1359
#define IDM_ABOUT                       40008
#define IDM_CLOSE                       40012
#define ID_DATEI_ERWITERTEEINSTELLUNGEN 40013
#define ID_DATEI_EINSTELLUNGENSPEICHERN_NEU 40015
#define ID_DATEI_EINSTELLUNGENLADEN_KEINE 40016
#define ID_FLOTTEN_SPEICHERN_ANGREIFER_NEU 40017
#define ID_FLOTTEN_SPEICHERN_VERTEIDIGER_NEU 40018
#define ID_FLOTTEN_LADEN_VERTEIDIGER_1  40020
#define ID_FLOTTEN_LADEN_ANGREIFER_1    40021
#define ID__WIEDERHERSTELLEN            40026
#define ID__SPEEDSIMBEENDEN             40027
#define ID_DATEI_TECHNOLOGIEENSPEICHERN 40028
#define ID_FLOTTEN_LSCHEN_KEINE         40029
#define ID_DATEI_EINSTELLUNGENLSCHEN_KEINE 40031
#define ID_SLOT1                        40032
#define ID_SLOT2                        40033
#define ID_SLOT3                        40034
#define ID_SLOT4                        40035
#define ID_SLOT5                        40036
#define ID_ENTER                        40037
#define ID_ESCAPE                       40038
#define ID_NEWINSTANCE                  40040
#define ID_SHOWOPTS                     40041
#define ID_LANGUAGE_DEUTSCH             40043
#define ID_TRAY_INFO                    40044
#define ID_FLOTTEN_ALLEFLOTTENSLOTSLEEREN 40045
#define ID_NEXTFLEET                    40046
#define ID_PREVFLEET                    40047
#define ID_SHOWPOPUP                    40048
#define IDM_ESPIO_MANAG                 40049
#define IDM_IPMMODE                     40050
#define ID_SHOW_HIST                    40051
#define IDM_SHOW_ESPHIST                40053
#define ID_EDIT_ESP                     40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40055
#define _APS_NEXT_CONTROL_VALUE         1360
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
